[package]
name = "disassembler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
arbitrary-int = "1.2.3"
bitbybit = "1.1.2"
bitvec = "1.0.1"
